export const DialogModeEnum = {
  SUB_SINGLE_ADD: "sub_single_add",
  SUB_MULTIPLE_ADD: "sub_multiple_add",
  MAIN_UPDATE: "main_update",
  CREATE_ACCOUNT: "create_account",
};
//  1: currentCurrency.jewellerOrb,
// 2: currentCurrency.chromaticOrb,
// 3: currentCurrency.orbOfFusing,
// 4: currentCurrency.orbOfTransmutation,
// 5: currentCurrency.orbOfChance,
// 6: currentCurrency.orbOfAlchemy,
// 7: currentCurrency.orbOfAugmentation,
// 8: currentCurrency.orbOfAlteration,
// 9: currentCurrency.exaltedOrb,
// 10: currentCurrency.chaosOrb,
// 11: currentCurrency.regalOrb,
// 12: currentCurrency.orbOfScouring,
// 13: currentCurrency.divineOrb,
// 14: currentCurrency.vaalOrb,
// 15: currentCurrency.mirrorOfKalandra,
// 16: currentCurrency.whetstone,
// 17: currentCurrency.armourersScrap,
// 18: currentCurrency.orbOfAnnulment,
export const CurrencyEnum = {
  jewellerOrb: 1,
  chromaticOrb: 2,
  orbOfFusing: 3,
  orbOfTransmutation: 4,
  orbOfChance: 5,
  orbOfAlchemy: 6,
  orbOfAugmentation: 7,
  orbOfAlteration: 8,
  exaltedOrb: 9,
  chaosOrb: 10,
  regalOrb: 11,
  orbOfScouring: 12,
  divineOrb: 13,
  vaalOrb: 14,
  mirrorOfKalandra: 15,
  whetstone: 16,
  armourersScrap: 17,
  orbOfAnnulment: 18,
};
